### PR TITLE
Update API's README to acknowledge `populate-users` script

### PR DESCRIPTION
**Pull request by Be-Like**
To reflect the changes related to #279.

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
Thanks for the PR @Be-Like! 💯

Should we wait to make the changes to the READMEs in the PR for #314? As we will be constantly adding more scripts, this way we don't have to keep updating them.

**Comment by Be-Like** [comment]
That works for me. You can go ahead and reject this PR.

**Comment by AlbertoPdRF** [comment]
Ok, let's forget about my previous comment. The main README will only need to be updated when #314 is taken care of, we can keep the back end one in sync while we keep adding scripts.

We can batch the README update with [this change](https://github.com/Tisn/tisn.app/pull/312#discussion_r499178240) and just merge it!

**Review by AlbertoPdRF — APPROVED** [review]
LGTM!

Merging now :man_technologist:

**Pull request merged**
